### ISSUE TITLE
Add a setter for machine type 

### ISSUE THREAD

**Issue by janetkuo** [GoogleCloudPlatform/anthos-service-mesh-packages#47]

**Comment by tibers** [comment]
Also my default pool consistently comes up as `n1-standard-1`, no matter what it's set to.

**Comment by RammusXu** [comment]
Hi, I'm trying to create a new setter for `machineType` by 
```bash
kpt cfg create-setter asm nodeConfig.machineType e2-standard-4
```

Why I get `{"$kpt-set":"nodeConfig.machineType"}` rather than `{"$ref":"#/definitions/io.k8s.cli.setters.gcloud.container.nodepool.max-nodes"}`?
Am i miss something? or where can I find the `"$ref":"#/definitions`?

```yaml
## Kptfile
    io.k8s.cli.setters.gcloud.container.nodepool.max-nodes:
      x-k8s-cli:
        setter:
          name: gcloud.container.nodepool.max-nodes
          value: "4"
    io.k8s.cli.setters.nodeConfig.machineType:
      x-k8s-cli:
        setter:
          name: nodeConfig.machineType
          value: e2-standard-4
## nodepool.yaml
  autoscaling:
    minNodeCount: 2
    maxNodeCount: 5 # {"$ref":"#/definitions/io.k8s.cli.setters.gcloud.container.nodepool.max-nodes"}
  nodeConfig:
    machineType: e2-standard-4 # {"$kpt-set":"nodeConfig.machineType"}
```
