### ISSUE TITLE
Add support for patched lifecycle prestop hook

### ISSUE THREAD

**Issue by DP19** [GoogleCloudPlatform/anthos-service-mesh-packages#876]
When moving from istio on gke (v1.4) using the supplied guide here:
https://cloud.google.com/istio/docs/istio-on-gke/migrate-to-anthos-service-mesh

It is suggested to use the google managed control plane, which suits most peoples needs. However, in the previous istio on gke install there is a patch to the istio-proxy:
`istio-sidecar-injector` configmap:
```yaml
  - name: istio-proxy
    # PATCH #2: Graceful shutdown of the istio-proxy. See https://github.com/istio/istio/issues/7136.
    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c", 'sleep 20; while [ $(netstat -plunt | grep tcp | grep -v envoy | wc -l | xargs) -ne 0 ]; do sleep 1; done']
    # PATCH #2 ends.
   ```
   This doesn't exist for the google managed control plane standard install; nor is it an option supplied in https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/tree/master/asm/istio/options
   
   Since you are unable to use a custom overlay with a managed control plane, it seems like the only options are to use the non managed control plane or to supply this option. It seems like this would have no effect on running the google managed control plane and a quick win for folks who what to keep this patch after migrated from istio on gke
