### ISSUE TITLE
Fix type of gcloud.container.nodepool.max-nodes

### ISSUE THREAD

**Issue by dayanyrec** [GoogleCloudPlatform/anthos-service-mesh-packages#92]
Hi folks!

When I set max-nodes to 5 using:
`kpt cfg set asm gcloud.container.nodepool.max-nodes 5`

I have an error:
`Error: The input value doesn't validate against provided OpenAPI schema: validation failure list:
gcloud.container.nodepool.max-nodes in body must be of type int: "integer"`

The same error occurs if I try to list the values using:
`kpt cfg list-setters asm/`

**Comment by dayanyrec** [comment]
I am just now reviewing this error and it works if I use _integer_ as type like this:

```
    io.k8s.cli.setters.gcloud.container.nodepool.max-nodes:
      type: integer
      x-k8s-cli:
        setter:
          name: gcloud.container.nodepool.max-nodes
          value: "2" 
```
